// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

#nullable disable

namespace Sylex.ISYS.Domain.Manufacture.Models
{
    public partial class ČíselníkMateriál
    {

        public ČíselníkMateriál()
        {
        
        }

        public int Id { get; }

        [Display(ShortName = "PN")]
        public string KódMateriálu { get; set; }

        public string Popis { get; set; }
        //public string Poznámka { get; set; }

        [Display(Name = "Merná jednotka", ShortName = "MJ")]
        public string MJ { get; set; }

        [Display(Name = "Poznámka pre sklad")]
        public string KódMolex { get; set; }
        public string Skupina { get; set; }

        /// <summary>
        /// see <see cref="MaterialType"/>
        /// </summary>
        public string Druh { get; set; }

        [Display(Name = "Kód dodávateľa")]
        public string KódDodavateľa { get; set; }
        public float? Zľava { get; set; }

        /// <summary>
        /// Vstupná kontrola: FOI/FOS 
        /// </summary>
        /// <seealso cref="InputQualityCheck.Department"/>
        [Display(Name = "Vstupná kontrola", ShortName = "VK", Description = "Oddelenie vstupnej kontroly")]
        public string Vkdept { get; set; }

        public string ZaložilMeno { get; set; }
        public DateTime? ZaložilDátumČas { get; set; }
        public string ZmenilMeno { get; set; }
        public DateTime? ZmenilDátumČas { get; set; }

        public int? PočetŽíl { get; set; }

     

        public int? ColnáPoložka { get; set; }

        //[Obsolete]
        //public double? Minimum { get; set; }

        //public string Umiestnenie { get; set; }

        /// <summary>Dodavatel</summary>
        [Display(Name = "Id Dodávateľa")]
        public int? IndexPartnera { get; set; }
        public double? CenaDodavateľa { get; set; }
        public string Mena { get; set; }
        public double? Kurz { get; set; }
        //public int? MenaKoeficient { get; set; }
        public bool Nezobrazovať { get; set; }

        /// <summary><see cref="Enums.ROHS"/></summary>
        public string ROHS { get; set; }
        //public int? PočetCievok { get; set; }
        //public bool? VyplniťPočetCievok { get; set; }
        /// <summary>
        /// udáva sa v gramoch/MJ
        /// </summary>
        public double? Hmotnosť { get; set; }


        /// <summary>
        /// číslo projektu
        /// </summary>
        [Display(Name = "CRM/QPN")]
        public string CQ { get; set; }

        [Display(Name = "Použiteľný zvyšok kábla", ShortName = "PZK")]
        public double? PoužiteľnýZvyšokKábla { get; set; }

        public string MOQ { get; set; }

        public string Revízia { get; set; }
        /// <summary>
        /// kód krajiny pôvodu
        /// </summary>
        public string Krajina { get; set; }
        //public DateTime? Rohsdate { get; set; }
        //public DateTime? Reachdate { get; set; }
        public bool Šaržovanie { get; set; }

        /// <summary>
        /// Call of Order
        /// </summary>
        [Display(Name = "Call of Order")]
        public string CofO { get; set; }

        [Display(Name = "Buffer Stock")]
        public string BufferStock { get; set; }
        public string CPR { get; set; }
        /// <summary>
        /// Conflict Minerals
        /// </summary>
        //public string Cm { get; set; }
        public string EUpreferencia { get; set; }
        public int? DodacíTermín { get; set; }
        public string Divízia { get; set; }

    }
}