// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using Sylex.ISYS.Domain.Manufacture.Models;
using Sylex.ISYS.Domain.Manufacture.Models.Custom;

namespace Sylex.ISYS.Domain.Manufacture.Configuration.Custom;

public class MaterialInfo2Configuration : IEntityTypeConfiguration<MaterialInfo2>
{
    public void Configure(EntityTypeBuilder<MaterialInfo2> entity)
    {
        entity.ToTable("ČíselníkMateriál");
        entity.HasKey(e => e.KódMateriálu);        
        entity.HasAlternateKey(e => e.Id);    
        
        entity.Property(e => e.KódMateriálu).HasColumnName("KódMateriálu").HasMaxLength(25);
        entity.Property(e => e.KódDodavateľa).HasColumnName("KódDodavateľa");
        entity.Property(e => e.Popis).HasColumnName("Popis");
        entity.Property(e => e.MJ).HasColumnName("MJ");
        entity.Property(e => e.Druh).HasColumnName("Druh");


        entity.HasOne<ČíselníkMateriál>()
            .WithOne()
            .IsRequired(false)
            .HasForeignKey<MaterialInfo2>(e => e.KódMateriálu)
            .HasPrincipalKey<ČíselníkMateriál>(e => e.KódMateriálu)
            .HasConstraintName("FK_MaterialInfo2_ČíselníkMateriál_MaterialCode")
            .OnDelete(DeleteBehavior.Cascade);
    }   
}
